name: deploy-to-pypi

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload release to PyPi
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: build dependencies
        run: python -m pip install -U build

      - name: build
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
