name: pytest-macos

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"
        
    - name: Running tests with pytest
      run: |
        mkdir -p test-data/results
        pytest
        
    - name: Upload images from failed tests
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: failed-image-comparisons
        path: test-data/results
